export const links = [
    {  id:"section-1",
      label: "عن مدينتي",
      url: "/find-events",
      isMain: true,
      isActive: false,
      isWhite: true,
      withFake: true,
    },
    { id:"section-4",
      label: "خدمات مدينتي",
      url: "/moments",
      isMain: true,
      isActive: false,
      isWhite: false,
      withFake: false,
    },
    { id:"section-6",
      label: "دليل استخدام مدينتي",
      url: "/podcasts",
      isMain: true,
      isActive: false,
      isWhite: false,
      withFake: false,
    },
    { id:"section-5",
      label: "الشركاء",
      url: "/pricing",
      isActive: false,
      isMain: true,
      isWhite: true,
      withFake: true,
    },
    {
      id:"section-7",
      label: "التواصل",
      url: "/contact-us",
      isMain: true,
      isActive: false,
      isWhite: false,
      withFake: false,
    },
];

export const contacts=[
  {id:0 , icon:"/assets/tel.svg", value:"+216 58949005"},
  {id:1 , icon:"/assets/email.svg", value:"gmail@gmail.com"},
  {id:2 , icon:"/assets/address.svg", value:"Adress Here"},

]